# Generated by Django 6.0.4 on 2026-05-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='digital',
        ),
    ]
