# Generated by Django 6.0.4 on 2026-05-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='digital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
