# Generated by Django 6.0.4 on 2026-05-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_digital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='digital',
            new_name='entrega',
        ),
    ]
