# Generated by Django 6.0.4 on 2026-06-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_rol_remove_direcciondespacho_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_disp',
            field=models.IntegerField(default=0),
        ),
    ]
