# Generated by Django 6.0.4 on 2026-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='id_transaccion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
